name: Sync Notion Content 5a

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

permissions:
  contents: write # Ensures write permissions for GITHUB_TOKEN

jobs:
  fetch-notion-content:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full history for pull/rebase

      # Step 2: Reset NPM Registry and Clean Cache
      - name: Reset to Alternative NPM Registry
        run: |
          npm config set registry https://skimdb.npmjs.com/registry
          npm cache clean --force

      # Step 3: Debug Network Access
      - name: Debug Network Access
        run: |
          echo "Testing network access..."
          curl -v https://registry.npmjs.org/
          curl -v https://registry.npmjs.org/@notionhq/client || echo "Failed to reach NPM registry"
          curl -v https://www.google.com

      # Step 4: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 5: Install dependencies with fallback
      - name: Install dependencies
        working-directory: ./project
        run: |
          npm install || echo "Primary install failed, trying direct GitHub install"
          npm install https://github.com/makenotion/notion-sdk-js || echo "Direct install failed, check network issues"

      # Step 6: Fetch Notion Content (Debugging Output)
      - name: Fetch Notion Content
        working-directory: ./project
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        run: |
          node notion-sync.js > notion-output.log
          echo "Fetched Notion Content:"
          cat notion-output.log || echo "Failed to fetch Notion content"

      # Step 7: Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # Step 8: Stage Changes and Pull Remote Changes
      - name: Stage Changes and Pull Remote
        run: |
          git add -A
          git stash push -m "Temp stash before pull" || true
          git fetch origin main
          git pull --rebase origin main || true
          git stash pop || true

      # Step 9: Track Changes and Debug
      - name: Track Changes
        run: |
          echo "Staging Files for Commit:"
          git status
          git add -A
          git status

      # Step 10: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git commit -m "Update: Fetched new Notion content" --allow-empty
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 11: Confirm Push Success
      - name: Confirm Push Success
        run: |
          echo "Latest commit:"
          git log -1
